function t270_scroll(hash,offset){if(!hash)return;if(hash.indexOf('#!/tproduct/')!==-1||hash.indexOf('#!/tab/')!==-1){return!0}
var target;try{if(hash.substring(0,1)==='#'){target=document.getElementById(hash.substring(1))}else{target=document.querySelector(hash)}}catch(event){console.log('Exception t270: '+event.message);return!0}
if(!target){target=document.querySelector('a[name="'+hash.substr(1)+'"]');if(!target)return!0}
var isHistoryChangeAllowed=window.location.hash!==hash;var wrapperBlock=document.querySelector('.t270');var dontChangeHistory=wrapperBlock?Boolean(wrapperBlock.getAttribute('data-history-disabled')):!1;target=parseInt(target.getBoundingClientRect().top+window.pageYOffset-offset,10);var isSafari=/constructor/i.test(window.HTMLElement)||(function(p){return p.toString()==='[object SafariRemoteNotification]'})(!window.safari||(typeof safari!=='undefined'&&window.safari.pushNotification));var isIE=!1||!!document.documentMode;if(isSafari||isIE){t_throttle(t270_scrollToEl(target),500)}else{t_throttle(window.scrollTo({left:0,top:target,behavior:'smooth',}),500)}
if(!dontChangeHistory&&isHistoryChangeAllowed){if(history.pushState){history.pushState(null,null,hash)}else{window.location.hash=hash}
isHistoryChangeAllowed=!1}
return!0}
function t270_scrollToEl(target){var duration=400;var start=(window.pageYOffset||document.documentElement.scrollTop)-(document.documentElement.clientTop||0);var change=target-start;var currentTime=0;var increment=16;document.body.setAttribute('data-scrollable','true');function t270__easeInOutCubic(currentTime){if((currentTime/=duration/2)<1){return(change/2)*currentTime*currentTime*currentTime+start}else{return(change/2)*((currentTime-=2)*currentTime*currentTime+2)+start}}
function t270__animateScroll(){currentTime+=increment;window.scrollTo(0,t270__easeInOutCubic(currentTime));if(currentTime<duration){setTimeout(t270__animateScroll,increment)}else{document.body.removeAttribute('data-scrollable')}}
t270__animateScroll()}
function t657_init(recid){var rec=document.querySelector('#rec'+recid);if(!rec)return;var wrapperBlock=rec.querySelector('.t657');var closeButton=rec.querySelector('.t657__btn');var closeIcon=rec.querySelector('.t657__icon-close');var storageItem=wrapperBlock.getAttribute('data-storage-item');var lastOpen;if(typeof localStorage==='object'){try{lastOpen=localStorage.getItem(storageItem)}catch(error){console.log('Your web browser does not support localStorage. Error status: ',error)}}
if(!lastOpen){wrapperBlock.classList.remove('t657_closed')}
wrapperBlock.addEventListener('click',function(event){if(event.target===closeButton||event.target===closeIcon){wrapperBlock.classList.add('t657_closed');if(typeof localStorage==='object'){try{localStorage.setItem(storageItem,Math.floor(Date.now()/1000))}catch(error){console.log('Your web browser does not support localStorage. Error status: ',error)}}}
event.preventDefault()})}
function t821_init(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var menu=rec?rec.querySelector('.t821'):null;if(!menu)return;var isFixed=menu.style.position==='fixed'||window.getComputedStyle(menu).position==='fixed';var isRedactorMode=menu.classList.contains('t821_redactor-mode');if(!isRedactorMode){menu.classList.remove('t821__beforeready');if(isFixed&&menu.getAttribute('data-bgopacity-two')){t821_changebgopacitymenu();window.addEventListener('scroll',t_throttle(function(){t821_changebgopacitymenu()},200))}
if(isFixed&&menu.getAttribute('data-appearoffset')){menu.classList.remove('t821__beforeready');t821_appearMenu();window.addEventListener('scroll',t_throttle(function(){t821_appearMenu()},200))}}
t821_setBg();window.addEventListener('resize',t_throttle(function(){t821_setBg()},200))}
function t821_setBg(){var menuBlocks=document.querySelectorAll('.t821');Array.prototype.forEach.call(menuBlocks,function(menu){if(window.innerWidth>980){if(menu.getAttribute('data-bgcolor-setbyscript')==='yes'){menu.style.backgroundColor=menu.getAttribute('data-bgcolor-rgba')}}else{menu.style.backgroundColor=menu.getAttribute('data-bgcolor-hex');menu.setAttribute('data-bgcolor-setbyscript','yes');if(menu.style.transform)menu.style.transform='';if(menu.style.opacity)menu.style.opacity=''}})}
function t821_appearMenu(){if(window.innerWidth<=980)return;var menuBlocks=document.querySelectorAll('.t821');Array.prototype.forEach.call(menuBlocks,function(menu){var appearOffset=menu.getAttribute('data-appearoffset');if(appearOffset){if(appearOffset.indexOf('vh')!==-1){appearOffset=Math.floor((window.innerHeight*(parseInt(appearOffset)/100)))}
appearOffset=parseInt(appearOffset,10);var menuHeight=menu.clientHeight;if(typeof appearOffset==='number'&&window.pageYOffset>=appearOffset){if(menu.style.transform==='translateY(-'+menuHeight+'px)'){t821_slideUpElement(menu,menuHeight,'toBottom')}}else if(menu.style.transform==='translateY(0px)'){t821_slideUpElement(menu,menuHeight,'toTop')}else{menu.style.transform='translateY(-'+menuHeight+'px)';menu.style.opacity='0'}}})}
function t821_slideUpElement(menu,menuHeight,position){var diff=position==='toTop'?0:menuHeight;var diffOpacity=position==='toTop'?1:0;var timerID=setInterval(function(){menu.style.transform='translateY(-'+diff+'px)';menu.style.opacity=diffOpacity.toString();diffOpacity=position==='toTop'?diffOpacity-0.1:diffOpacity+0.1;diff=position==='toTop'?diff+(menuHeight/20):diff-(menuHeight/20);if(position==='toTop'&&diff>=menuHeight){menu.style.transform='translateY(-'+menuHeight+'px)';menu.style.opacity='0';clearInterval(timerID)}
if(position==='toBottom'&&diff<=0){menu.style.transform='translateY(0px)';menu.style.opacity='1';clearInterval(timerID)}},10)}
function t821_changebgopacitymenu(){if(window.innerWidth<=980)return;var menuBlocks=document.querySelectorAll('.t821');Array.prototype.forEach.call(menuBlocks,function(menu){var bgColor=menu.getAttribute('data-bgcolor-rgba');var bgColorAfterScroll=menu.getAttribute('data-bgcolor-rgba-afterscroll');var bgOpacity=menu.getAttribute('data-bgopacity');var bgOpacityTwo=menu.getAttribute('data-bgopacity-two');var menuShadow=menu.getAttribute('data-menushadow')||'0';var menuShadowValue=menuShadow==='100'?menuShadow:'0.'+menuShadow;menu.style.backgroundColor=window.pageYOffset>20?bgColorAfterScroll:bgColor;if(window.pageYOffset>20&&bgOpacityTwo==='0'||window.pageYOffset<=20&&bgOpacity==='0.0'||menuShadow===' '){menu.style.boxShadow='none'}else{menu.style.boxShadow='0px 1px 3px rgba(0,0,0,'+menuShadowValue+')'}})}
function t821_createMobileMenu(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var menu=rec.querySelector('.t821');var burger=rec.querySelector('.t821__mobile');if(burger){burger.addEventListener('click',function(){if(burger.classList.contains('t821_opened')){t821_fadeOut(menu,300);burger.classList.remove('t821_opened')}else{t821_fadeIn(menu,300,function(){if(menu.style.transform)menu.style.transform='';if(menu.style.opacity)menu.style.opacity=''});burger.classList.add('t821_opened')}})}
window.addEventListener('resize',t_throttle(function(){if(window.innerWidth>980){if(menu.style.opacity)menu.style.opacity='';if(menu.style.display==='none')menu.style.display=''}else{if(menu.style.transform)menu.style.transform=''}},200))}
function t821_fadeOut(element,duration,callback){if(!element)return!1;var opacity=1;duration=parseInt(duration,10);var speed=duration>0?duration/10:40;var timer=setInterval(function(){element.style.opacity=opacity;opacity-=0.1;if(opacity<=0.1){element.style.opacity='0';element.style.display='none';if(typeof callback==='function'){callback()}
clearInterval(timer)}},speed)}
function t821_fadeIn(element,duration,callback){if(!element)return!1;if((getComputedStyle(element).opacity==='1'||getComputedStyle(element).opacity==='')&&getComputedStyle(element).display!=='none')return!1;var opacity=0;duration=parseInt(duration,10);var speed=duration>0?duration/10:40;element.style.opacity=opacity;element.style.display='block';var timer=setInterval(function(){element.style.opacity=opacity;opacity+=0.1;if(opacity>=1){element.style.opacity='1';if(typeof callback==='function'){callback()}
clearInterval(timer)}},speed)}
function t886_init(recid){var rec=document.querySelector('#rec'+recid);if(!rec)return;var notificationBlock=rec.querySelector('.t886');var closeButton=rec.querySelector('.t886__btn');var storageItem=notificationBlock.getAttribute('data-storage-item');var lastOpen=null;if(typeof localStorage==='object'){try{lastOpen=localStorage.getItem(storageItem)}catch(error){console.log('Your web browser does not support localStorage. Error status: ',error)}}
if(!lastOpen){notificationBlock.classList.remove('t886_closed')}
if(closeButton){closeButton.addEventListener('click',function(event){notificationBlock.classList.add('t886_closed');if(typeof localStorage==='object'){try{localStorage.setItem(storageItem,Math.floor(Date.now()/1000))}catch(error){console.log('Your web browser does not support localStorage. Error status: ',error)}}
event.preventDefault()})}}